#include <iostream>
#include <map>
#include <list>
#include <string>
using namespace std;
/*
"61137":
    {"61139":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":0,"INHERITED_FROM":"11"},
    "61143":{"SHORT_DESCRIPTION":true,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":true,"SORT":1,"INHERITED_FROM":"11"},
    "SORT":1,
    "INHERITED_FROM":"11"},

"61159":
    {"61161":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":false,"SORT":3,"INHERITED_FROM":"11"},
    "61163":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":false,"SORT":4,"INHERITED_FROM":"11"},
    "61165":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":13,"INHERITED_FROM":"11"},
    "61167":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":false,"SORT":0,"INHERITED_FROM":"11"},
    "61173":{"SHORT_DESCRIPTION":true,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":true,"SORT":5,"INHERITED_FROM":"11"},
    "61175":{"SHORT_DESCRIPTION":true,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":7,"INHERITED_FROM":"11"},
    "61177":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":9,"INHERITED_FROM":"11"},
    "61181":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":10,"INHERITED_FROM":"11"},
    "61183":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":12,"INHERITED_FROM":"11"},
    "61839":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":1,"INHERITED_FROM":"11"},
    "61841":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":14,"INHERITED_FROM":"11"},
    "61843":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":2,"INHERITED_FROM":"11"},
    "67609":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":8,"INHERITED_FROM":"11"},
    "235504":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":11,"INHERITED_FROM":"11"},
    "343846":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":true,"SORT":6,"INHERITED_FROM":"11"},
    "369676":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":15,"INHERITED_FROM":"11"},
    "SORT":0,"INHERITED_FROM":"11"},

"61279":
{"61185":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":0,"INHERITED_FROM":"11"},
"61187":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":11,"INHERITED_FROM":"11"},
"61193":{"SHORT_DESCRIPTION":true,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":true,"SORT":1,"INHERITED_FROM":"11"},
"61195":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":12,"INHERITED_FROM":"11"},
"61197":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":6,"INHERITED_FROM":"11"},
"61199":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":14,"INHERITED_FROM":"11"},
"61201":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":15,"INHERITED_FROM":"11"},
"61203":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":16,"INHERITED_FROM":"11"},
"61231":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":17,"INHERITED_FROM":"11"},
"61233":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":18,"INHERITED_FROM":"11"},
"61235":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":19,"INHERITED_FROM":"11"},
"61237":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":20,"INHERITED_FROM":"11"},
"61239":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":21,"INHERITED_FROM":"11"},
"61241":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":22,"INHERITED_FROM":"11"},
"61243":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":24,"INHERITED_FROM":"11"},
"61245":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":25,"INHERITED_FROM":"11"},
"61247":{"SHORT_DESCRIPTION":true,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SHOW_IN_LIST":true,"SORT":2,"INHERITED_FROM":"11"},
"61277":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":26,"INHERITED_FROM":"11"},
"171852":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":7,"INHERITED_FROM":"11"},
"234340":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":13,"INHERITED_FROM":"11"},
"241261":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":3,"INHERITED_FROM":"11"},
"241264":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":8,"INHERITED_FROM":"11"},
"281134":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":4,"INHERITED_FROM":"11"},
"281137":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":9,"INHERITED_FROM":"11"},
"307384":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":5,"INHERITED_FROM":"11"},
"307414":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":10,"INHERITED_FROM":"11"},
"329050":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":27,"INHERITED_FROM":"11"},
"369664":{"SHORT_DESCRIPTION":false,"IS_REQUIRED":false,"IS_SEARCHABLE":false,"IS_COMPARABLE":false,"IS_HIDDEN":false,"SORT":23,"INHERITED_FROM":"11"},
"SORT":3,"INHERITED_FROM":"11"},
*/
int main()
{




//    list<map<int,map<string,string>>> hueta =
//    auto hueta =
//    {61137,
//    {"61139",{{"SHORT_DESCRIPTION","false"},{"IS_REQUIRED","false"},{"IS_SEARCHABLE","false"},{"IS_COMPARABLE","false"},{"IS_HIDDEN","false"},{"SORT","0"},{"INHERITED_FROM","11"}},
//    "61143",{{"SHORT_DESCRIPTION","true"},{"IS_REQUIRED","false"},{"IS_SEARCHABLE","false"},{"IS_COMPARABLE","false"},{"IS_HIDDEN","false"},{"SHOW_IN_LIST","true"},{"SORT","1"},{"INHERITED_FROM","11"}},
//    "SORT",{"1"},
//    "INHERITED_FROM",{"11"}}};


//    auto hueta =
//    {61137,
//    {"61139",{{"SHORT_DESCRIPTION","false"},{"IS_REQUIRED","false"},{"IS_SEARCHABLE","false"},{"IS_COMPARABLE","false"},{"IS_HIDDEN","false"},{"SORT","0"},{"INHERITED_FROM","11"}},
//    "61143",{{"SHORT_DESCRIPTION","true"},{"IS_REQUIRED","false"},{"IS_SEARCHABLE","false"},{"IS_COMPARABLE","false"},{"IS_HIDDEN","false"},{"SHOW_IN_LIST","true"},{"SORT","1"},{"INHERITED_FROM","11"}},
//    "SORT",{"1"},
//    "INHERITED_FROM",{"11"}}};


    map<int, string> hueta2 = {{61137, "61139"}, {61143, "61139"}};
//    map<int, map<string,string>> hueta3 = { {61137, {"61139", "SHORT_DESCRIPTION"}}, {61137, {"61139", "SHORT_DESCRIPTION"}} };
    auto hueta3 = { {61137, {"61139", "SHORT_DESCRIPTION"}}, {61137, {"61139", "SHORT_DESCRIPTION"}} };





    return 0;
}
